name: Update HTML File

on:
  push:
    branches:
      - main # main 브랜치에 푸시할 때마다 트리거됨
    paths:
      - "today/*" # today 폴더 내의 모든 파일이 변경될 때만 실행

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update HTML Files
        run: |
          echo "파일 수정 중..."
          # 예시로 간단한 수정 작업을 추가
          echo "<!-- 자동 업데이트된 내용 -->" >> today/monday.html
          git config --global user.name "GitHub Actions"
          git config --global user.email "your-email@example.com"
          git add today/*
          git commit -m "자동 업데이트: 오늘의 일정"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub 토큰을 GitHub Actions 비밀값으로 설정
